import type { AIProvider, AIProviderResult, GenerateContentInput, CampaignGenerationInput, AICampaignProviderResult } from "../types";
import { validateGeneratedContent } from "../schema";
import { validateGeneratedCampaign } from "../campaign-schema";
import { validateContentScore } from "@/lib/intelligence/schema";
export class OpenAIProvider implements AIProvider {
  readonly name = "openai"; private readonly apiKey: string; private readonly model: string;
  constructor(apiKey: string, model = process.env.OPENAI_MODEL || "gpt-4o-mini") { this.apiKey = apiKey; this.model = model; }
  private async request(body: Record<string, unknown>) { const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${this.apiKey}` }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(`OpenAI request failed (${response.status}).`); const data = await response.json() as { choices?: Array<{ message?: { content?: string } }> }; const raw = data.choices?.[0]?.message?.content; if (!raw) throw new Error("OpenAI returned an empty response."); try { return JSON.parse(raw) as unknown; } catch { throw new Error("OpenAI returned invalid JSON."); } }
  async generateContent(input: GenerateContentInput): Promise<AIProviderResult> { const parsed = await this.request({ model: this.model, temperature: 0.8, response_format: { type: "json_object" }, messages: [{ role: "system", content: "Return only valid JSON with exactly these keys: hook, caption, cta, hashtags, imagePrompt. hashtags must be an array of 5 to 15 hashtag strings. No markdown." }, { role: "user", content: JSON.stringify(input) }] }); return { provider: this.name, model: this.model, content: validateGeneratedContent(parsed) }; }
  async generateCampaign(input: CampaignGenerationInput): Promise<AICampaignProviderResult> { const parsed = await this.request({ model: this.model, temperature: 0.8, response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a senior social campaign strategist. Return only JSON with exactly: title and days. days must contain exactly the requested duration. Each day must have contentIdea, hook, caption, cta, hashtags (array), imagePrompt, suggestedDate. Use the supplied dates. No markdown." }, { role: "user", content: JSON.stringify(input) }] }); return { provider: this.name, model: this.model, campaign: validateGeneratedCampaign(parsed, input.duration) }; }
  async scoreContent(input: import("../types").ScoreContentInput): Promise<import("../types").ContentScoreResult> {
    const parsed = await this.request({ model: this.model, temperature: 0.2, response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a social content strategist. Return only valid JSON with exactly: score, breakdown, recommendations. score and each breakdown field must be integers 0-100. breakdown keys: hookStrength, readability, ctaStrength, platformSuitability, audienceRelevance, hashtagQuality. recommendations must be an array of concise strings." }, { role: "user", content: JSON.stringify(input) }] });
    return { provider: this.name, model: this.model, score: validateContentScore(parsed) };
  }
}
